[webservers]
webserver1 ansible_host=51.159.150.9 ansible_user=root ansible_port=22 domain_name=calbor-p42-cloud.duckdns.org
webserver2 ansible_host=24.199.120.225 ansible_user=root ansible_port=22 domain_name=calbor-p42-cloud2.duckdns.org

[serv1]
webserver1 ansible_host=51.159.150.9 ansible_user=root ansible_port=22 domain_name=calbor-p42-cloud.duckdns.org

[serv2]
webserver2 ansible_host=24.199.120.225 ansible_user=root ansible_port=22 domain_name=calbor-p42-cloud2.duckdns.org
